// <auto-generated />
//
// To parse this JSON data, add NuGet 'Newtonsoft.Json' then do:
//
//    using QuickType;
//
//    var responseObj = ResponseObj.FromJson(jsonString);

namespace APIVerve.API.FillintheBlanksGenerator
{
    using System;
    using System.Collections.Generic;

    using System.Globalization;
    using Newtonsoft.Json;
    using Newtonsoft.Json.Converters;

    public partial class ResponseObj
    {
        [JsonProperty("status")]
        public string Status { get; set; }

        [JsonProperty("error")]
        public object Error { get; set; }

        [JsonProperty("data")]
        public Data Data { get; set; }
    }

    public partial class Data
    {
        [JsonProperty("puzzles")]
        public Puzzle[] Puzzles { get; set; }

        [JsonProperty("count")]
        public long Count { get; set; }

        [JsonProperty("difficulty")]
        public string Difficulty { get; set; }

        [JsonProperty("category")]
        public string Category { get; set; }

        [JsonProperty("html")]
        public string Html { get; set; }
    }

    public partial class Puzzle
    {
        [JsonProperty("id")]
        public long Id { get; set; }

        [JsonProperty("sentence")]
        public string Sentence { get; set; }

        [JsonProperty("answer")]
        public string Answer { get; set; }

        [JsonProperty("letterCount")]
        public long LetterCount { get; set; }

        [JsonProperty("hint")]
        public string Hint { get; set; }

        [JsonProperty("firstLetter")]
        public object FirstLetter { get; set; }
    }
}
